import { defineConfig } from "oxlint";

export const react = defineConfig({
  plugins: ["react", "react-perf"],
  rules: {
    "react/button-has-type": ["error"],
    "react/checked-requires-onchange-or-readonly": ["error"],
    "react/display-name": ["error"],
    "react/exhaustive-deps": ["error"],
    "react/forbid-component-props": ["off"],
    "react/forbid-dom-props": ["off"],
    "react/forbid-elements": ["off"],
    "react/forward-ref-uses-ref": ["error"],
    "react/hook-use-state": ["error"],
    "react/iframe-missing-sandbox": ["error"],
    "react/jsx-boolean-value": ["error", "never", { assumeUndefinedIsFalse: false }],
    "react/jsx-curly-brace-presence": [
      "error",
      { children: "never", propElementValues: "never", props: "never" }
    ],
    "react/jsx-filename-extension": [
      "error",
      { allow: "as-needed", extensions: ["jsx", "tsx"], ignoreFilesWithoutCode: true }
    ],
    "react/jsx-fragments": ["error", "syntax"],
    "react/jsx-handler-names": ["off"],
    "react/jsx-key": ["error"],
    "react/jsx-max-depth": ["error", { max: 5 }],
    "react/jsx-no-comment-textnodes": ["error"],
    "react/jsx-no-constructed-context-values": ["error"],
    "react/jsx-no-duplicate-props": ["error"],
    "react/jsx-no-literals": ["off"],
    "react/jsx-no-script-url": ["error"],
    "react/jsx-no-target-blank": ["error"],
    "react/jsx-no-undef": ["error"],
    "react/jsx-no-useless-fragment": ["error"],
    "react/jsx-pascal-case": ["error"],
    "react/jsx-props-no-spread-multi": ["error"],
    "react/jsx-props-no-spreading": ["error"],
    "react/no-array-index-key": ["off"],
    "react/no-children-prop": ["error"],
    "react/no-clone-element": ["error"],
    "react/no-danger": ["error"],
    "react/no-danger-with-children": ["error"],
    "react/no-did-mount-set-state": ["error"],
    "react/no-did-update-set-state": ["error"],
    "react/no-direct-mutation-state": ["error"],
    "react/no-find-dom-node": ["error"],
    "react/no-is-mounted": ["error"],
    "react/no-multi-comp": ["error"],
    "react/no-namespace": ["error"],
    "react/no-object-type-as-default-prop": ["error"],
    "react/no-react-children": ["error"],
    "react/no-redundant-should-component-update": ["error"],
    "react/no-render-return-value": ["error"],
    "react/no-set-state": ["error"],
    "react/no-string-refs": ["error"],
    "react/no-this-in-sfc": ["error"],
    "react/no-unescaped-entities": ["error"],
    "react/no-unknown-property": ["error"],
    "react/no-unsafe": ["error"],
    "react/no-unstable-nested-components": ["error"],
    "react/no-will-update-set-state": ["error"],
    "react/only-export-components": ["error"],
    "react/prefer-es6-class": ["off"],
    "react/prefer-function-component": ["error"],
    "react/react-compiler": ["off"],
    "react/react-in-jsx-scope": ["off"],
    "react/require-render-return": ["error"],
    "react/rules-of-hooks": ["error"],
    "react/self-closing-comp": ["error"],
    "react/state-in-constructor": ["error"],
    "react/style-prop-object": ["error"],
    "react/void-dom-elements-no-children": ["error"],
    "react-perf/jsx-no-jsx-as-prop": ["error"],
    "react-perf/jsx-no-new-array-as-prop": ["error"],
    "react-perf/jsx-no-new-function-as-prop": ["error"],
    "react-perf/jsx-no-new-object-as-prop": ["error"]
  }
});
